/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainInterface;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.stream.Collectors;


/**
 *
 * @author Lasith
 */
public class Dictionary extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary
     */
    public Dictionary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputSearch.setText("Search a word here");
        inputSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputSearchMouseClicked(evt);
            }
        });
        jPanel1.add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 440, 40));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 120, 40));

        resultText.setEditable(false);
        resultText.setColumns(20);
        resultText.setLineWrap(true);
        resultText.setRows(15);
        resultText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(resultText);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 570, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String word = inputSearch.getText();

        try {
            String url = "https://api.dictionaryapi.dev/api/v2/entries/en/" + word;
            String text = new BufferedReader(
                    new InputStreamReader(new URL(url).openStream(), StandardCharsets.UTF_8))
                    .lines()
                    .collect(Collectors.joining("\n"));
            JsonElement jsonElement = JsonParser.parseString(text);
            JsonArray jsonArray = jsonElement.getAsJsonArray();

            //check whether has data
            if (jsonArray.size() > 0) {
                String result = "";
                JsonObject obj = jsonArray.get(0).getAsJsonObject();
                //have a big object
                //need to get into meanings array and parse it

                //tap into meanings array and get object from the array
                //needs a loop to travese on all objects available in meaning
                JsonArray meaningArray = obj.get("meanings").getAsJsonArray();
                JsonObject meaningObject;
                for (int i = 0; i < meaningArray.size(); i++) {
                    //looping through the meaning array
                    meaningObject = meaningArray.get(i).getAsJsonObject();

                    //setting the partof speech
                    String partOfString = meaningObject.get("partOfSpeech").toString().replace("\"", "").replace("\\", "");
                    result += " -- " + partOfString.toUpperCase() + "\n";

                    JsonArray definitionArray = meaningObject.get("definitions").getAsJsonArray();
                    JsonObject definitionObject;

                    for (int k = 0; k < definitionArray.size(); k++) {

                        definitionObject = definitionArray.get(k).getAsJsonObject();

                        try {
                            String means = definitionObject.get("definition").toString().replace("\"", "").replace("\\", "");
                            //each definition has an example that can be read
                            try {
                                String example = definitionObject.get("example").toString().replace("\"", "").replace("\\", "");
                                result += "   •" + means + "\n";
                                result += "          Eg:-" + example + "\n";

                                System.out.println(result);
                                resultText.setText(result);
                            }
                            catch(Exception e){
                                
                            }
                        }catch(Exception e){
                            resultText.setText("No definitions");
                        }

                    }

                }

                //definitions are again in a json array 
                //needs to repeat the same operation
            }

        } catch (Exception e) {
            resultText.setText("No results found. Please check your spellings");
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void inputSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSearchMouseClicked
        // TODO add your handling code here:
         inputSearch.setText("");
    }//GEN-LAST:event_inputSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultText;
    // End of variables declaration//GEN-END:variables
}
